# Generated by Django 5.1.2 on 2024-11-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0004_section_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
    ]
