# Generated by Django 5.1.2 on 2024-11-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0005_lecture_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='dynamic_course_path'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic_course_path'),
        ),
    ]
