# Generated by Django 5.1.1 on 2025-01-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0006_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
    ]
