# Generated by Django 5.1.2 on 2024-11-26 17:36

import userEx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0007_course_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to=userEx.models.dynamic_course_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=userEx.models.dynamic_course_path),
        ),
    ]
