# Generated by Django 5.1.1 on 2024-12-03 17:42

import userEx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0009_alter_course_intro_video_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to=userEx.models.dynamic_course_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=userEx.models.dynamic_course_path),
        ),
    ]
